rasterizer_cpp:
	g++ -o rasterizer hw2_math_ops.cpp hw2_file_ops.cpp rasterizer.cpp 

run:
	./rasterizer ../inputs/culling_enabled_inputs/horse_and_mug/horse_and_mug_scene.txt ../inputs/culling_enabled_inputs/horse_and_mug/horse_and_mug_camera.txt

clean:
	rm -rf *.ppm *.png ./rasterizer
